### ISSUE TITLE
Whole root filesystem is accessible

### ISSUE THREAD

**Issue by jeroenst** [axiom-data-science/rsync-server#25]
When I list the files on the rsyncd server the whole root file system is accessible. I would expect only /data would be accessible.

```
rsync -e 'ssh -p 874' root@server:/
The authenticity of host '[server]:874 ([81.172.135.49]:874)' can't be established.
ED25519 key fingerprint is SHA256:XXXX.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[server]:874' (ED25519) to the list of known hosts.
root@server's password: 
drwxr-xr-x          4,096 2024/09/09 10:33:11 .
-rwxr-xr-x              0 2024/09/09 10:33:10 .dockerenv
-rwxr-xr-x          1,140 2023/04/11 19:14:07 entrypoint.sh
drwxr-xr-x          4,096 2023/04/11 19:14:14 bin
drwxr-xr-x          4,096 2022/12/09 20:15:00 boot
drwxr-xr-x            244 2024/09/09 10:27:46 data
drwxr-xr-x            340 2024/09/09 10:33:11 dev
drwxr-xr-x          4,096 2024/09/09 10:33:11 etc
drwxr-xr-x          4,096 2022/12/09 20:15:00 home
drwxr-xr-x          4,096 2023/04/11 19:14:14 lib
drwxr-xr-x          4,096 2023/03/20 01:00:00 lib64
drwxr-xr-x          4,096 2023/03/20 01:00:00 media
drwxr-xr-x          4,096 2023/03/20 01:00:00 mnt
drwxr-xr-x          4,096 2023/03/20 01:00:00 opt
dr-xr-xr-x              0 2024/09/09 10:33:11 proc
drwx------          4,096 2024/09/09 10:33:11 root
drwxr-xr-x          4,096 2024/09/09 10:33:33 run
drwxr-xr-x          4,096 2023/04/11 19:14:14 sbin
drwxr-xr-x          4,096 2023/03/20 01:00:00 srv
dr-xr-xr-x              0 2024/09/09 10:33:11 sys
drwxrwxrwt          4,096 2023/03/20 01:00:00 tmp
drwxr-xr-x          4,096 2023/03/20 01:00:00 usr
drwxr-xr-x          4,096 2023/03/20 01:00:00 var
```

Docker compose:
```
  rsync-server-vps01:
    container_name: rsync-server-vps01
    image: axiom/rsync-server
    restart: unless-stopped
    ports:
      - '874:22'
    volumes:
      - '/mnt/hd1/rsync/vps01:/data'
    environment:
      - 'TZ=Europe/Amsterdam'
      - 'PASSWORD=XXXXX'
```
